import { Box, Button, IconButton, Menu, MenuButton, MenuItem, MenuList, Stack, Text } from "@chakra-ui/react"
import { Providers } from "./provider"
import Image from "next/image"
import { HamburgerMenu } from "./(main)/UI/icons"
import Link from "next/link"


export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
	return (
		<html>
			<body>
				<Providers>
					<Box w="full" borderBottomWidth="thin" borderColor="blackAlpha.200" shadow="sm" p="5">
						<Stack direction="row" justify="space-between" alignItems="center">
							<Link href="/collections">
								<Stack direction="row" spacing="" alignItems="flex-end">
									<Image src="/haven-realty-logo.png" height="1" width="120" alt="Haven Realty Logo" />
									<Text fontSize="lg" fontWeight="semibold">Help Center</Text>
								</Stack>
							</Link>
							<Box display={[ "none", "none", "inline-block"]}>
								<Button variant="ghost" size="sm">Log In</Button>
								<Button variant="ghost" size="sm">Sign Up</Button>
							</Box>
							<Box display={[ "inline-block", "inline-block", "none" ]}>
								<Menu>
									<MenuButton as={IconButton} icon={<HamburgerMenu fontSize="xl" />} variant="ghost" size="md" />

									<MenuList>
										<Link href="/">
											<MenuItem>Log In</MenuItem>
										</Link>
										<Link href="/sign-up">
											<MenuItem>Sign Up</MenuItem>
										</Link>
									</MenuList>
								</Menu>
							</Box>
						</Stack>
					</Box>
					{children}
				</Providers>
			</body>
		</html>
	)
}
